# PyTorch Fundamentals

## Importing PyTorch

In [1]:
import torch
torch.__version__

'2.1.1'

## Tensor

Tensors are multi-dimensional matrices.  
PyTorch tensors are objects of the `torch.Tensor` class.

## Scalar

Scalars are zero-dimensional tensors, or in other words, tensors that hold a single element.

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

The `item()` method returns the singular element of a scalar.  
It only works for scalars.

In [4]:
scalar.item()

7

## Vector

Vectors are one-dimensional tensors.

In [5]:
vector = torch.tensor([5, 3])
vector.shape

torch.Size([2])

## Matrix

Matrices are two-dimensional tensors.  
It is conventional to name matrices and tensors using upppercase, whereas scalars and vectors are named using lowercase.  
The terms matrix and tensor are often used interchangably.

In [6]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX.shape

torch.Size([2, 2])

## Initialising tensors

In [7]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9313, 0.1934, 0.6566, 0.2459],
         [0.5499, 0.4679, 0.0675, 0.7508],
         [0.7135, 0.9406, 0.5915, 0.7928]]),
 torch.float32)

In [8]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range

In [10]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating a likeness

In [11]:
zeros = torch.zeros_like(zero_to_ten)
ones = torch.ones_like(zero_to_ten)
zeros, ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

## Datatypes

The most common and default datatype is `torch.float32` or `torch.float`.  
`torch.float16` is also called `torch.half`.  
`torch.float64` is also called `torch.double`.  
The default value of the `dtype` attribute is `torch.float32`.  
The `requires_grad` attribute is set to `True` if we want the operations on the tensor to be recorded.

In [12]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device=None, requires_grad=False)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

## Getting information from tensors

In [13]:
sample_tensor = torch.rand(3, 4)
print(sample_tensor)
print(f"Shape of tensor: {sample_tensor.shape}")
print(f"Datatype of tensor: {sample_tensor.dtype}")
print(f"Device of tensor: {sample_tensor.device}")

tensor([[0.5049, 0.3474, 0.3609, 0.8262],
        [0.4244, 0.8764, 0.5433, 0.0974],
        [0.4528, 0.0295, 0.7070, 0.9635]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


## Operations on tensors

In [14]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [15]:
tensor * 10

tensor([10, 20, 30])

In [16]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication

There are two rules for performing matrix multiplication.  
The inner dimensions must match - `(3, 2) @ (2, 4)` works as the inner dimensions are both `2`.  
The resulting matrix has the shape of the outer dimensions - `(3, 2) @ (2, 4)` results in a matrix of dimensions `(3, 4)`.

In [17]:
A = torch.rand(3, 2)
B = torch.rand(2, 4)
A @ B

tensor([[0.6711, 0.1180, 0.1420, 0.3883],
        [0.4877, 0.6636, 0.6915, 0.1632],
        [0.5012, 0.2416, 0.2623, 0.2584]])

In [18]:
torch.matmul(A, B)

tensor([[0.6711, 0.1180, 0.1420, 0.3883],
        [0.4877, 0.6636, 0.6915, 0.1632],
        [0.5012, 0.2416, 0.2623, 0.2584]])

In [19]:
t = torch.tensor([1, 2, 3])
torch.matmul(t, t)

tensor(14)

In [20]:
A = torch.rand(3, 2)
B = torch.rand(3, 2)
torch.mm(A, B.T)

tensor([[0.3155, 0.9062, 0.9156],
        [0.3223, 0.6401, 0.6029],
        [0.3414, 0.9485, 0.9534]])

`torch.nn.Linear` implements matrix multiplication between an input layer `x` and a weights matrix `A`.  
The operation it performs is represented by the equation $y = x \cdot A^T + b$.
The `manual_seed()` method is used for seeding, to ensure that the code that follows always produces the same output, despite the linear layer relying on random weights and biases.

In [21]:
torch.manual_seed(30)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
linear(x)

tensor([[1.8126, 0.8936, 0.6832, 0.6857, 1.4842, 0.0325],
        [3.6429, 1.8705, 2.1661, 2.1521, 2.2470, 1.0608],
        [5.4732, 2.8474, 3.6489, 3.6184, 3.0098, 2.0891]],
       grad_fn=<AddmmBackward0>)